### ISSUE TITLE
Problem with Dropdown tabs

### ISSUE THREAD

**Issue by r00d1k** [docusign/docusign-esign-php-client#138]
I faced with fatal error when I fetch Tab list from template's document which contain dropdown. In Tabs model defined `'list_tabs' => '\DocuSign\eSign\Model\array[]',` but this model doesn't exist. But I found unused \DocuSign\eSign\Model\ModelList which fits better to process this data.
There is pull request with fix. https://github.com/docusign/docusign-esign-php-client/pull/137

**Comment by ORudenkoAS** [comment]
Hello. Kindly remind you to check my pull request. it would be grateful if you add this fix in official repo.

**Comment by r00d1k** [comment]
Hello. Kindly remind you to check my pull request. it would be grateful if you add this fix in official repo.

**Comment by dbbrahmbhatt** [comment]
Hi @r00d1k . Thank you for reporting the issue. Fix has been added to the latest PHP releases 6.2.0 (for v2.1) and 4.10.0 for (v2).
