### ISSUE TITLE
Not working on php 8+

### ISSUE THREAD

**Issue by Theo4** [docusign/docusign-esign-php-client#165]
Hello,

Trying to use the lib on a php8+ version and it doesn't work. A lot of deprecated notice and impossible to authenticate are main problems.

Is there any planned update ?

Thank you,

**Comment by plezan** [comment]
Hello, we also have have this deprecations notice :
```Return type of DocuSign\eSign\Model\*** should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice```
on every Docusign model using offsets :
- `offsetSet($offset, $value)`
- `offsetUnset($offset)`
- `offsetExists($offset)`
- `offsetGet($offset)`

Do you think it's possible to use `the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice` while you get this issue fixed ?

Thanks

**Comment by dbbrahmbhatt** [comment]
Thank you for filing the issue. We are currently working on the fix for this. Update will be posted here once the fix is shipped.

**Comment by dbbrahmbhatt** [comment]
Issue has been fixed using `#[\ReturnTypeWillChange]` attribute in release [6.7.1](https://github.com/docusign/docusign-esign-php-client/releases/tag/v6.7.1)
