### ISSUE TITLE
ApiClient refreshAccessToken throw ApiException with code 400

### ISSUE THREAD

**Issue by unicorn610** [docusign/docusign-esign-php-client#171]
I call the refreshAccessToken method with client_id, client_secret, refresh_token, but get 400 code of response. After failing, I successfully using same value to get new token by postman.

The error message is "Error while requesting server, received a non successful HTTP code [400] with response Body:  O:8:"stdClass":1:{s:5:"error";s:15:"invalid_request";}"

**Comment by ivdinkovds** [comment]
Hi @unicorn610, As far as I know, the [API Client](https://github.com/docusign/docusign-esign-csharp-client/blob/master/sdk/src/DocuSign.eSign/Client/ApiClient.cs) does not have a call for a refresh token.  Would you be able to share the method and expand on where you are seeing this method?

**Comment by karankaushik95** [comment]
Hey, this sounds like it could use a bit more investigation. Could you open a support ticket with us: https://support.docusign.com/s/contactSupport?language=en_US&rsc_301 so my developer support team can investigate this further?

**Comment by unicorn610** [comment]
Hi, is the support only for paid customer? My developer account cannot login the support system. Currently, I'm helping my client to verify could this product meet their requirement.

**Comment by karankaushik95** [comment]
Hey - no not at all

On the page I linked, there's a tab for DocuSign API Integration Support with a form in it. If you fill that out, it will get sent to us.

**Comment by unicorn610** [comment]
After testing, I found the refresh token API (/oauth/token) only accept form-data but the method refreshAccessToken in ApiClient uses x-www-form-urlencoded. That's might be the reason why I got error [400] response. I got [200] response after I remove the 'Content-Type' => 'application/x-www-form-urlencoded'. Maybe you should check is the 
```
$headers = [ 
    "Authorization" => $integrator_and_secret_key, 
    "Content-Type" => "application/x-www-form-urlencoded", 
];
```
