### ISSUE TITLE
proxy setup

### ISSUE THREAD

**Issue by DeveloperOnePlus** [docusign/docusign-esign-php-client#184]
Hi,

I am trying to connect docusign from a corporate hosting. Issue I am facing is with proxy setup

Error I am getting is (since connection can be made only via proxy): 
 Failed to connect to account-d.docusign.com port 443 after 130615 ms: Connection timed out

I tried adding proxyHost and port like,

 $docusignConfig->setCurlProxyHost($config->proxyHost);
 $docusignConfig->setCurlProxyPort($config->proxyPort);

But not helping either.

Any guidence appreciated.

Thanks
D

**Comment by kamran-bhatti** [comment]
Hi, 

I think to begin with, what you will want to do is verify from your logging that you are in fact having an issue via your proxy with hitting the docusign site. From there consult with your local IT infrastructure team to ensure that there's nothing locally blocking you. Finally, when all potential local issues are resolved and if you're still having an issue, open a support ticket with DocuSign and a support representative will help you out. 

-Kamran.

**Comment by shan285** [comment]
Hi @DeveloperOnePlus ,

I wanted to check in regarding the solution/suggestion provided to address the proxy issue. Could you please let me know if the issue is resolved or if there are any outstanding concerns?

Thank you for your time and assistance.

-Shashanka

**Comment by shan285** [comment]
Hi @DeveloperOnePlus 
We wanted to follow up on your proxy issue. As we have not heard back from you, we hope that the solution we provided has resolved your issue.

We will be closing this ticket assuming the problem has been resolved. If the issue persists or if you need any further assistance, please do not hesitate to reopen this ticket or create a new one. 

-Shashanka
