### ISSUE TITLE
QUESTION: Error on JWT Grant Authentication with SDK

### ISSUE THREAD

**Issue by samuel-lujan** [docusign/docusign-esign-php-client#187]
`Error: invalid_grant error_description issuer_not_found`

Hello, I'm trying to connect with Docusign API using de SDK, to create an envelope, but on executing the method "requestJWTUserToken" or "requestJWTApplicationToken" with my correct credentials, got this error.

![image](https://user-images.githubusercontent.com/17858893/210374368-18e067b7-b275-4ea9-9e6b-826df441681b.png)

![image](https://user-images.githubusercontent.com/17858893/210374439-7f145d39-ba7f-4077-aa4f-a628d64b6f8d.png)

**Comment by Adrian-DS-Support** [comment]
Hi Samuel, 

The issuer is the integration key (DocuSign-ClientID). 
Please make sure the env('DDOCUSIGN_CLIENT_ID') is providing the integration key you created in your DocuSign "Settings- Apps & Keys" page and that it's not missing any characters. 

We hope this helps. 

Adrian
DocuSign Developer Support

**Comment by bastien70** [comment]
Hello, I've exactly the same problem, and I think I put the good information.

```php
        $integratorKey = '(this is the integrator key on my docusign app, see number 2 in the screenshots)';
        $userId = '(this is my user_id key on the developer dashboard, see number 1 in the screenshot)';
        $privateKey = file_get_contents(__DIR__ . '/private_key'); // This is the privateKey generated in the app (Check number 3 i n screenshot, I've a keypair. I'm not using the keypair, but the long privateKey so it's okay)
        $scope = ApiClient::$SCOPE_SIGNATURE;
        $config = new Configuration();
        $config->setHost('https://demo.docusign.net/restapi');
        $apiClient = new ApiClient($config);

//        $apiClient->getOAuth()->setOAuthBasePath()

        try {
            $userToken = $apiClient->requestJWTUserToken($integratorKey, $userId, $privateKey, $scope);
            dd($userToken);
        } catch (\Throwable $th)
        {
            dd($th->getMessage(), $th->getTrace());
        }
```

And I've exactly the same error message that @samuel-lujan 

![image](https://user-images.githubusercontent.com/53140475/213156962-a3366a88-d192-412a-b7ec-dd5477263117.png)

This is my app details : 
![image](https://user-images.githubusercontent.com/53140475/213157272-4d5c9d16-2cda-4453-b778-a66f6806f572.png)

**Comment by samuel-lujan** [comment]
Thanks man! this helped me a lot! :)

**Comment by bastien70** [comment]
Wait, I've the problem too xDD

**Comment by samuel-lujan** [comment]
You can add me at discord SamuelLujan#7764

**Comment by bastien70** [comment]
Yeaah, you are the best :P I added you :)

**Comment by samuel-lujan** [comment]
We did some call and solve the error! The error is caused because your application is not allowed to use your integration key on docusign. You first need to go into this [link](https://developers.docusign.com/platform/auth/consent/obtaining-individual-consent/#:~:text=Every%20DocuSign%20workflow%20requires%20that,See%20the%20list%20of%20scopes.) where you can create an URL to give permission to your application. After this you need to set in your ApiClient the oauthBaseUrl with this code: 
`$this->docusignApiClient->getOAuth()->setOAuthBasePath("account-d.docusign.com");` and after this you done. you can go on and create the envelope @bastien70 did and call with me and can help me if did I forgot something
