### ISSUE TITLE
Open To View Signed Envelopes

### ISSUE THREAD

**Issue by samuel-lujan** [docusign/docusign-esign-php-client#195]
Hello I have some envelope that I create via API, and I want to give a button to the user on frontend click and go to the signed envelope, to download or visualizate files. But I didn't found nothing.

**Comment by cbsdsdevsup** [comment]
Hi Samuel,

Thank you for contacting DocuSign Developer Support.

Please take a look at the following resources with regards to your questions:

**How to download envelope documents﻿**: https://developers.docusign.com/docs/esign-rest-api/how-to/download-envelope-documents/
**Embedded signature and elastic signing**: https://developers.docusign.com/docs/esign-rest-api/esign101/concepts/embedding/

Let me know if there is anything else you need.

Kind regards,
Conar | DocuSign Developer Support

**Comment by samuel-lujan** [comment]
Thanks for the help!
