### ISSUE TITLE
QUESTION | How to create some field populated by signer 

### ISSUE THREAD

**Issue by samuel-lujan** [docusign/docusign-esign-php-client#197]
So I'm using the API to create an envelope with some documents, and I want to create some field to the signer put your registration number on the created document and after this sign the document and the envelope is that possible? I should use CustomFields or nameValues I'm so confused.

**Comment by karankaushik95** [comment]
So I'm not sure what you're looking to do. Are you looking to place a tab for the signer to be able to fill in some values by themselves or are you looking to supply tabs to them with a filled in value? 
You can use a text tab in either case. 

If its the latter case, this is what you're looking for - https://developers.docusign.com/docs/esign-rest-api/how-to/set-envelope-tab-values/

If its the former case, you can still use the same guide but just omit the "value" parameter which will let the signer fill it in. 

For a more detailed guide, please open a [Support Case](https://support.docusign.com/s/contactSupport?language=en_US&Channels=7)

**Comment by karankaushik95** [comment]
When creating the tab, you can set the "required" parameter to true - https://developers.docusign.com/docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/create/#schema_201_enveloperecipienttabs_enveloperecipienttabs_texttabs_required
which will cause the tab to be required to be filled in by the signer at the time of signing.

**Comment by samuel-lujan** [comment]
Perfect I'll try it!

**Comment by samuel-lujan** [comment]
Updates! I'm trying to use the text_tabs, usign the SDK, but when I use the method to create the eSing/Text, to att as an text_tabs on the sdk and after this add on the document, this returns me an error, saying that the anchor_string is not correct. But all things are ok. And when I send with the text_tabs as an array unless the eSign/Text, I  don´t receive this error but the text is not transfered to the document

**Comment by karankaushik95** [comment]
Would you be able to open a Support case with [DocuSign Developer Support](https://support.docusign.com/s/contactSupport?language=en_US&Channels=7)? This would need some logs which need to be generated on your end which is better submitted through a Support case.

**Comment by samuel-lujan** [comment]
Solved it buddy! I was trying to add the tab on the document but I was not specifying the user. So then I created the tab to the user and all went well! Thanks for helping
