### ISSUE TITLE
QUESTION: Signers Order

### ISSUE THREAD

**Issue by samuel-lujan** [docusign/docusign-esign-php-client#200]
How can I set the user id X to be the first to sign, after the Y and then the next ones... One By One, try to find something on documentation but I so confused if this is a Signer configuration, or and Envelope Configuration.

**Comment by ashleyurena** [comment]
Hello Samuel,

The parameter is routingOrder and it is set in the recipients definition, here is an example:

"recipients": {
		"ssigner": [{
				"email": "ashleyu.dstest+edit@gmail.com",
				"name": "Lior",
				"recipientId": "1",
				"routingOrder": "1",
				},...
Also, here is our documentation: https://developers.docusign.com/docs/esign-rest-api/reference/envelopes/envelopes/create/

**Comment by samuel-lujan** [comment]
Pretty good! Thanks :)
