### ISSUE TITLE
Two Text Tabs With The Same Value

### ISSUE THREAD

**Issue by samuel-lujan** [docusign/docusign-esign-php-client#209]
I'm usign the docusign-esign-php-client to creante some envelopes. And I need in one envelope two add two text tabs one for the signer document and another for signer observations but I wrote the code like the first photo
![image](https://github.com/docusign/docusign-esign-php-client/assets/17858893/0caad8de-cb94-4184-97de-40b80ebd4109)

But when I'm signing the document, when I type into the first text tab the second text tab goes with the same value. What I'm doing wrong?

![image](https://github.com/docusign/docusign-esign-php-client/assets/17858893/7bb0efd3-080f-4b13-826f-2f90fa2f9c5a)

**Comment by InbarGazit** [comment]
Your code is wrong, change` tapLabel` to `tabLabel` and see if it fixes it

**Comment by samuel-lujan** [comment]
Thanks! And the key of array on Esign-PHP-Client is tab_label not TabLable. But with your help I fixed! Thanks :)
