### ISSUE TITLE
Signature PDF is not returning to WEB APP - PHP LARAVEL

### ISSUE THREAD

**Issue by awaisamir123** [docusign/docusign-esign-php-client#210]
DocuSign takes the PDF and is also signed by the signer after that I want to get this PDF back to save the local directory of my web App.

Is there any solution for it? As per research, DocuSign returns this PDF to the signer EMAIL. 

Anyone can help with it.

**Comment by docucrtest** [comment]
Hello @awaisamir123, by any chance, Can you share an envelopeID to check?

Thanks in advance

**Comment by mike-mej** [comment]
Hello @awaisamir123 By Any chance, Could you please share an envelopeId as a reference to check on my end?
Thanks in advance

**Comment by awaisamir123** [comment]
I am integrating the DocuSign API. How I can get the signed document back?

Process to sign a document -- I have a multi-step form. Suppose I want signature of user  at the step no 3. So, I have convert these HTML code to PDF. I have attached the PDF with DocuSign API. I want this signed document return back with my call back URL and store this locally. So, I want signature on 3 places in a single form. So this process will repeat. 

Like I will merge signed PDF 1 with the next steps PDF 2 so on.
Can you please provide any solution on it or any helping link for it. I don't want signing on docusign for a signature.

**Comment by mike-mej** [comment]
@awaisamir123 
Thanks for the clarification
Please check this:
https://developers.docusign.com/docs/esign-rest-api/how-to/download-envelope-documents/
https://developers.docusign.com/docs/esign-rest-api/reference/envelopes/envelopedocuments/get/

I hope this works for you.

**Comment by shan285** [comment]
Hi @awaisamir123 

I wanted to check in regarding the solution we provided to address the PDF issue. Could you please let me know if it resolved the issue or if there are any outstanding concerns?

Thank you for your time and assistance.

-Shashanka

**Comment by shan285** [comment]
Hi @awaisamir123 
We wanted to follow up on your PDF issue. As we have not heard back from you, we hope that the solution we provided has resolved your issue.

We will be closing this ticket assuming the problem has been resolved. If the issue persists or if you need any further assistance, please do not hesitate to reopen this ticket or create a new one. 

-Shashanka
