### ISSUE TITLE
Sandbox api end point is not working

### ISSUE THREAD

**Issue by sam110386** [docusign/docusign-esign-php-client#211]
anyone having issue with sandbox api end point. Its not working 

https://demo.docusign.com/restapi/v2.1/accounts

**Comment by Adrian-DS-Support** [comment]
Thank you for using DocuSign. 

We don't have any outages reported at this time. 

try this alternate URL:
https://demo.docusign.net/restapi/v2.1/

Regards
Adrian
DocuSign Developer Support

**Comment by garg-mudit** [comment]
Hi @sam110386,
Just checking if you managed to resolve the issues you were facing with the sandbox API.

Thank You.

**Comment by sam110386** [comment]
yes @garg-mudit 
i resolved that one
