### ISSUE TITLE
Dependency of abandoned bundle with 5 vulnerabilities

### ISSUE THREAD

**Issue by shtumi** [docusign/docusign-esign-php-client#221]
This bundle requires "firebase/php-jwt", which requires "guzzlehttp/guzzle",
The last one is abandoned and have 5 known vulnerabilities.

**Comment by saiharipriya** [comment]
Hello

In order to mitigate the vulnerabilities, regrettably, updating the dependency within the package to utilize an alternative would be necessary.

**Comment by saiharipriya** [comment]
.

**Comment by saiharipriya** [comment]
Hello

The SDK relies on specific packages with no flexibility to swap them out. If it can't be used due to dependency issues,  then please interact directly with our APIs instead.

Thankyou.

**Comment by shtumi** [comment]
I must admit, I'm truly impressed by your response. Do you also suggest discontinuing the use of DocuSign altogether?

You've presented two solutions for PHP users dealing with DocuSign:

Avoid using the PHP SDK.
Resort to a vulnerable solution.
This doesn't align with the expectations of a reputable company...

This SDK is a crucial component of DocuSign's service. We've invested significant time integrating DocuSign's functionality using this SDK, and naturally, we expect DocuSign to uphold their responsibility by providing continued support and maintaining the library in optimal condition. It's worth mentioning that DocuSign is not a free service.

I firmly believe that dedicating some developer resources to avoiding the use of vulnerable and neglected dependencies in your SDK is essential.

**Comment by saiharipriya** [comment]
Hello I Apologise, If I misunderstood the case, please let me check with our engineers & get back to you.

**Comment by saiharipriya** [comment]
Hello,

Could you please provide which version of SDK Package is being  used in your case?

Thanks
Sai

**Comment by garg-mudit** [comment]
Hi @shtumi,

I'm a member of the Docusign DevX team and responsible for improving the developer experience with our SDK. I agree with your assessment that there's room for significant improvements in our current SDKs.

I recently looked into potential vulnerabilities in the latest version of the eSign PHP SDK, both direct and through transitive dependencies. I used `composer audit --no-dev`, which, as far as I understand, also checks for vulnerabilities via transitive dependencies. Here are the results:

![image](https://github.com/docusign/docusign-esign-php-client/assets/35302867/6c6f8109-35f2-4b69-9844-1b8fa6caae64)

Based on this assessment, I didn't find any vulnerabilities in the eSign package. Please feel free to correct me if I'm mistaken.

At the same time, I also want to acknowledge that there are abandoned transitive dependencies listed under require-dev. However, to the best of my knowledge, these dependencies don't impact or introduce any vulnerabilities to the eSign package.

Please don't hesitate to correct me if you think I'm mistaken, and I'm open to discussing potential solutions.

Thank You.

**Comment by garg-mudit** [comment]
> This bundle requires "firebase/php-jwt", which requires "guzzlehttp/guzzle",

It seems you're confused between two similar packages: [guzzlehttp/guzzle](https://packagist.org/packages/guzzlehttp/guzzle) and [guzzle/guzzle](https://packagist.org/packages/guzzle/guzzle).

As you mentioned, the latest version of the SDK relies on `firebase/php-jwt` (version ^6.0.0), which in turn requires `guzzlehttp/guzzle`.

Notably, `guzzle/guzzle` is an abandoned package, replaced by `guzzlehttp/guzzle`.

![image](https://github.com/docusign/docusign-esign-php-client/assets/35302867/38c441c3-795a-4781-8fa2-ad77920cdc50)

![image](https://github.com/docusign/docusign-esign-php-client/assets/35302867/b5b4ae69-c7fe-4619-acd6-3e6f2a624216)

Currently, the mentioned package (i.e. `guzzle/guzzle`)  is only included in `required-dev`.
 
Based on this information and my last message, there doesn't seem to be a vulnerability within the eSign PHP SDK package. Please correct me if I'm mistaken. I'm here to assist with any further concerns. 

Thank you.

**Comment by shtumi** [comment]
In my composer.json I just included this lib as:
`"docusign/esign-client": "*",`
which loads v6.19.0

Then composer automatically loads firebase/php-jwt of version v6.10.0 from your dependencies
which then requires `"guzzlehttp/guzzle": "^6.5||^7.4",`

Then when I run `composer audit` it displays 
![2024-05-10_08-57-51](https://github.com/docusign/docusign-esign-php-client/assets/604334/0609a29c-4b89-4d44-9a26-d2a283512fa1)

**Comment by shtumi** [comment]
It's weird, but if I add `"guzzlehttp/guzzle": "7.8.1",` to my composer.json, it solves the problem.
May be it is related to local cache.
