### ISSUE TITLE
Signature Tabs Shifted Up After Upgrading from ^4.0 to ^6.12.0

### ISSUE THREAD

**Issue by sanycmi** [docusign/docusign-esign-php-client#233]
**Description:**

After upgrading from docusign/esign-client version ^4.0 to ^6.12.0, we noticed that all the signature tabs (SignHereTab) in our documents have shifted up by a few spots. This issue was not present in version ^4.0.

**Environment:**

- PHP Version: 8.2.22
- CakePHP Version: 4.5.5
- DocuSign/eSign Client Version: ^6.12.0
- Previous DocuSign/eSign Client Version: ^4.0
- OS: Linux

**Code Sample:**

Here is the relevant part of our code that was working fine with version ^4.0 but started showing issues after the upgrade:

```
public function addTabs(int $document_id, int $prior_pages): void {
    DocuSignTabs::add(new \DocuSign\eSign\Model\SignHere([
        'document_id' => $document_id,
        'recipient_id' => 3,
        'tab_label' => 'SignHereTab',
        'page_number' => $prior_pages + 1,
        'x_position' => 110,
        'y_position' => 185,
    ]));
}
```

**Issue Description:**

- After upgrading to version ^6.12.0, all SignHereTab elements in the documents have shifted upwards, compared to their positions when using version ^4.0.
- We use specific x_position and y_position values to position the tabs, but these positions appear to be handled differently in the new version.

**Impact:**

This issue affects multiple files where we would now need to manually update the y_position to correct the tab alignment. Given the number of files impacted, this is not a practical solution.

**Steps to Reproduce:**

- Use the code snippet above in a CakePHP project.
- Generate a document using DocuSign/eSign client version ^4.0.
- Upgrade to version ^6.12.0.
- Generate the same document and observe the position of the `SignHereTab`.

**Expected Behavior:**

- The `SignHereTab` should be positioned exactly where specified by the x_position and y_position values, as it was in version ^4.0.

**Actual Behavior:**

- The `SignHereTab` appears higher than the specified y_position, resulting in a misalignment of the signature tab in the document.

**Additional Context:**

- Manually adjusting the y_position in each affected file is not a viable long-term solution due to the large number of files impacted.
- We are looking for a more scalable workaround or a fix that can address this issue across all files without requiring manual updates.

**Request:**

Could you please provide any guidance on how to resolve this issue or suggest a workaround that would avoid having to manually adjust the x_position and y_position in multiple files? Any insights or documentation references would be greatly appreciated.

**Comment by esilva600** [comment]
Hello Sany,

During the upgrade from Rest API from 2.0 to 2.1 it resulted in changes to the tag processing. To fix this, you need to rearrange the offsets to display as expected. 

You can find more details in our documentation related to this update and the changes:
https://developers.docusign.com/docs/esign-rest-api/esign101/upgrading-v21/

Thanks,

**Comment by sanycmi** [comment]
Thanks to the documentation provided by @esilva600, we were able to implement an offset of 21 for SignHere and 16 for InitialHere. We achieved this by utilizing a wrapper, which allowed us to apply these adjustments without needing to modify every instance where they were used.
